sudo: required

service:
  - docker
#this is a comment

before_install:
  - docker build -t alirezazekvat\Calculator -f Dockerfile.dev .


script:
  - docker run alirezazekvat\Calculator npm run coverage
